//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeonBoard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeonBoardEntities : DbContext
    {
        public NeonBoardEntities()
            : base("name=NeonBoardEntities")
        {
        }
        private static NeonBoardEntities _context;
        public static NeonBoardEntities GetContext()
        {
            if (_context == null)
                _context = new NeonBoardEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseMaterial> BaseMaterial { get; set; }
        public virtual DbSet<BaseType> BaseType { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Signboard> Signboard { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
