//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeonBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Signboard()
        {
            this.Order1 = new HashSet<Order>();
        }
    
        public int IdBoard { get; set; }
        public int Type { get; set; }
        public int Material { get; set; }
        public int BaseHeight { get; set; }
        public int BaseWidth { get; set; }
        public int NeonLength { get; set; }
        public int CountOfElements { get; set; }
        public string Sketch { get; set; }
    
        public virtual BaseMaterial BaseMaterial { get; set; }
        public virtual BaseType Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
